name: Проверка кода при пуше

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Копируем код из Git в облако
        uses: actions/checkout@v4

      # Изменение 1: Мы запускаем тесты и просим pytest сгенерировать HTML-отчёт внутри контейнера.
      # Чтобы вытащить файл из контейнера на диск виртуальной машины, мы используем команду docker cp.
      - name: Запускаем автотесты и сохраняем отчёт
        run: |
          docker build -t my-python-app .
          docker run --name my-container my-python-app pytest --html=report.html --self-contained-html || true
          docker cp my-container:/app/report.html ./report.html

      # Изменение 2: Специальный готовый робот от GitHub, который берет файл report.html и сохраняет его в артефакты сборки.
      # Этот шаг сработает ВСЕГДА (даже если тесты упали), благодаря строчке always()
      - name: Загружаем HTML отчёт в артефакты GitHub
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report # Как будет называться архив на сайте
          path: ./report.html      # Какой файл забрать