# 1. Как будет называться наш процесс в интерфейсе GitHub
name: Проверка кода при пуше

# 2. Триггер: когда запускать робота?
on: [push] # Запускать при каждом 'git push' (когда мы отправляем код на сайт)

# 3. Список задач, которые должен сделать робот
jobs:
  run-tests: # Название нашей задачи (можно любое английское слово)
    # На каком компьютере запускать? 
    # GitHub бесплатно выделяет нам в облаке свой сервер на базе чистой Ubuntu Linux!
    runs-on: ubuntu-latest

    # Пошаговый план действий для этого компьютера:
    steps:
      # Шаг 2.1: Скачиваем наш код из репозитория на этот облачный компьютер
      - name: Копируем код из Git в облако
        uses: actions/checkout@v4 # Это готовый стандартный скрипт от GitHub

      # Шаг 2.2: Собираем Docker-образ (точно так же, как ты делал в PowerShell!)
      - name: Собираем Докер-образ
        run: docker build -t my-python-app .

      # Шаг 2.3: Запускаем тесты внутри собранного контейнера
      - name: Запускаем автотесты
        run: docker run my-python-app pytest